### ISSUE TITLE
Standalone server

### ISSUE THREAD

**Issue by mjackson** [unpkg/express-unpkg#66]
One of the immediately actionable ideas that came out of #65 is to create a standalone development server for unpkg, so people can run it on their own machines. I envision this being a small binary with the following API:

```
unpkg [registryURL] [-p port]
```

This would launch an HTTP server on the given port that serves packages out of npm. If we also include the index page, it could possibly be used to serve unpkg.com as well.

**Comment by alexisvincent** [comment]
Awesome :D once this is done let me know and I'll make an automated docker container

**Comment by mjackson** [comment]
This issue was moved to unpkg/unpkg.com#36
