### ISSUE TITLE
support JSONP

### ISSUE THREAD

**Issue by mihailik** [unpkg/express-unpkg#67]
While it's brilliant to be able to run `<script src="http://unpkg.com/..."></script>` from browser, even in security-restricted origins like `file://`, I want more!

Please add support for fetching the library content (source or text/readme/css) with JSONP-style callbacks.

Perhaps simply allow URL with `?jsonp=...` or `?callback=...` suffix.

    https://unpkg.com/typescript@2.2.1/lib/watchGuard.js?callback=withScriptContent

HTTP GET returning:

    withScriptContent({
       "package": "typescript",
       "version": "2.2.1",
       "encoding": "utf8",
       "content": "/*! ***********\n Copyright (c) Microsoft Corporation....."
    });

To make it complete and neat, it would support encoding type: defaults to text for `.js`, `.md`, `.css`,`.html` files and base64 for `.png`, `.jpg` etc. And also: support JSONP fetch of the whole package zipped and base64-ed.

# Please! ❤️

**Comment by mjackson** [comment]
That's an interesting idea :) I'd welcome discussing this further in a PR if you'd care to give it a shot. Although you're the first person who has ever asked for it, so it would be good to hear from some others who would also like the feature first.
