### ISSUE TITLE
Empty file returned for a package (guillotine@1.3.1)

### ISSUE THREAD

**Issue by whipermr5** [unpkg/express-unpkg#70]
Relevant URL: https://unpkg.com/guillotine@1.3.1/js/jquery.guillotine.min.js

I can access it just fine from where I am (Singapore), but in an [AppVeyor build environment](https://ci.appveyor.com/project/whipermr5/teammates/build/1.0.32) (based on the IP, U.S.?), it's returning a content length of zero:
<img width="596" alt="screen shot 2017-04-20 at 9 22 27 pm" src="https://cloud.githubusercontent.com/assets/6811428/25233316/0a85ac12-2611-11e7-9b1b-31b18c333fcd.png">

It seems to be the same issue as #56 - bad cache? If needed, I have another build with more verbose `curl` output [here](https://ci.appveyor.com/project/whipermr5/teammates/build/1.0.33).

**Comment by mjackson** [comment]
Yep, it looks like the cache has a 0-length response for that file. I can initiate a purge of the cache at that path, but I'm ultimately not sure the best method to prevent stuff like this from happening in the future. A very small percentage of requests to the origin servers fail for various reasons (timeouts, etc.), maybe the request from this edge node was one of them.

**Comment by mjackson** [comment]
OK, just initiated a purge for that file. Should be clear in 30 seconds.

**Comment by whipermr5** [comment]
@mjackson Thank you!! The builds are working now :)

**Comment by whipermr5** [comment]
@mjackson I've been playing around with my own `express-unpkg` instance and Cloudflare in an attempt to reproduce the zero length response cache, but have not been successful.

I have tried engineering my own timeouts, premature closed connections, etc. but Cloudflare does not cache those. The only thing that has worked so far is manually setting `stats.size` to `0` before `res.writeHead` in `sendFile`.

I noticed how `Content-Type`, `Cache-Control` and `ETag` are all cached correctly. The `ETag`, however, is different for the zero length response. It really makes it seem like the `stats` object was somehow bad when the server responded to the request for that particular edge node, resulting in a different `ETag` (since this is also calculated from `stats`) and a `Content-Length` of `0`.

Do you have origin server logs to check if this has ever happened?

**Comment by mjackson** [comment]
Great detective work, @whipermr5! 🕵️ 

Unfortunately I don't have detailed logs from the origin for 200 responses, only 40x and 50x. I'll setup a filter to try and catch this kind of thing the next time it happens.
